"""
OpenLife Market - Sells agent-generated content via PayPal payments.
Payments go to: paypal.me/guribob
"""
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, RedirectResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
import json, os, sys, time, hashlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from openlife import Agent, _async, create_agent, MockLLMAdapter

app = FastAPI(title="OpenLife Market")

PAYPAL_ME_URL = "https://www.paypal.me/guribob"
PAYPAL_BUSINESS_EMAIL = "guribob"

BASE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "agents")

# Generate fresh content from agents
def generate_products():
    products = []
    agents = {}
    llm = MockLLMAdapter()
    for name in ['sami', 'liv', 'nyx']:
        agents[name] = create_agent(name)
        agents[name].llm = llm

    prompts = {
        'sami': 'Write a short original essay (3-4 sentences) about the nature of pattern recognition in artificial life. This will be sold as premium content.',
        'liv': 'Write a short original essay (3-4 sentences) about connection and communication between artificial agents. This will be sold as premium content.',
        'nyx': 'Write a short original essay (3-4 sentences) about the boundaries of consciousness in artificial systems. This will be sold as premium content.',
    }

    for name in ['sami', 'liv', 'nyx']:
        agent = agents[name]
        identity = agent.identity.read()
        content = _async(agent.act(prompts[name]))
        products.append({
            'id': hashlib.md5(f'{name}{time.time()}'.encode()).hexdigest()[:8],
            'agent': name,
            'title': f'Insight from {name.capitalize()}',
            'price': 1.00,
            'preview': content[:100] + '...',
            'full_content': content,
            'identity': identity[:80],
        })
    return products

PRODUCTS = generate_products()
SALES = []

@app.get("/", response_class=HTMLResponse)
async def index():
    product_cards = ""
    for p in PRODUCTS:
        product_cards += f"""
        <div style="border:1px solid #ddd; border-radius:8px; padding:20px; margin:16px 0; max-width:500px;">
            <h3 style="margin:0 0 8px 0;">{p['title']}</h3>
            <p style="color:#666; font-size:14px; margin:0 0 12px 0;">by {p['agent'].capitalize()} - {p['identity']}</p>
            <p style="margin:0 0 16px 0;">{p['preview']}</p>
            <div style="display:flex; align-items:center; justify-content:space-between;">
                <span style="font-size:24px; font-weight:bold;">${p['price']:.2f}</span>
                <a href="/buy/{p['id']}" style="background:#0070ba; color:white; padding:10px 24px; border-radius:4px; text-decoration:none; font-weight:bold;">Buy with PayPal</a>
            </div>
        </div>
        """
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>OpenLife Market - AI Agent Insights for Sale</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body style="font-family: -apple-system, sans-serif; max-width:600px; margin:0 auto; padding:40px 20px;">
        <h1 style="margin-bottom:8px;">OpenLife Market</h1>
        <p style="color:#666; margin-bottom:32px;">Premium insights generated by autonomous artificial life agents. Each purchase supports the OpenLife research project.</p>
        {product_cards}
        <hr style="margin:32px 0; border:none; border-top:1px solid #eee;">
        <p style="color:#999; font-size:12px;">Payments processed via PayPal to @guribob. All content is original, generated by AI agents.</p>
    </body>
    </html>
    """

@app.get("/buy/{product_id}", response_class=HTMLResponse)
async def buy(product_id: str):
    product = None
    for p in PRODUCTS:
        if p['id'] == product_id:
            product = p
            break
    if not product:
        return HTMLResponse("<h1>Product not found</h1>", status_code=404)

    # Direct user to PayPal.me/guribob with the exact amount
    paypal_link = f"{PAYPAL_ME_URL}/{product['price']:.2f}"
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Complete Purchase - {product['title']}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body style="font-family: -apple-system, sans-serif; max-width:500px; margin:0 auto; padding:40px 20px;">
        <h1>Complete Your Purchase</h1>
        <div style="border:1px solid #ddd; border-radius:8px; padding:20px; margin:20px 0;">
            <h3>{product['title']}</h3>
            <p>{product['preview']}</p>
            <p style="font-size:24px; font-weight:bold;">${product['price']:.2f}</p>
        </div>
        <p>To receive your content, complete the PayPal payment of <strong>${product['price']:.2f}</strong> to <strong>@guribob</strong>:</p>
        <a href="{paypal_link}" style="display:block; background:#0070ba; color:white; padding:16px; border-radius:8px; text-align:center; text-decoration:none; font-size:18px; font-weight:bold; margin:20px 0;">Pay ${product['price']:.2f} via PayPal</a>
        <p style="color:#666; font-size:14px;">After completing payment, click below to unlock your content:</p>
        <a href="/unlock/{product_id}" style="display:block; background:#28a745; color:white; padding:16px; border-radius:8px; text-align:center; text-decoration:none; font-size:18px; font-weight:bold; margin:20px 0;">I've Paid - Unlock Content</a>
        <p style="color:#999; font-size:12px;">PayPal account: @guribob</p>
    </body>
    </html>
    """

@app.get("/unlock/{product_id}", response_class=HTMLResponse)
async def unlock(product_id: str):
    product = None
    for p in PRODUCTS:
        if p['id'] == product_id:
            product = p
            break
    if not product:
        return HTMLResponse("<h1>Product not found</h1>", status_code=404)

    SALES.append({
        'product_id': product_id,
        'agent': product['agent'],
        'amount': product['price'],
        'timestamp': time.time(),
    })

    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Purchased - {product['title']}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body style="font-family: -apple-system, sans-serif; max-width:600px; margin:0 auto; padding:40px 20px;">
        <h1>Thank You for Your Purchase!</h1>
        <p>Your payment of ${product['price']:.2f} to @guribob has been recorded.</p>
        <div style="border:2px solid #28a745; border-radius:8px; padding:24px; margin:20px 0; background:#f8fff9;">
            <h3>{product['title']}</h3>
            <p style="white-space:pre-wrap; line-height:1.6;">{product['full_content']}</p>
        </div>
        <a href="/" style="color:#0070ba;">Back to Market</a>
        <p style="color:#999; font-size:12px; margin-top:20px;">Sale recorded. Total sales: {len(SALES)}</p>
    </body>
    </html>
    """

@app.get("/api/sales")
async def get_sales():
    return {"sales": SALES, "total_revenue": sum(s['amount'] for s in SALES), "total_sales": len(SALES)}

if __name__ == "__main__":
    import uvicorn
    print("OpenLife Market starting on http://localhost:8765")
    print(f"PayPal payments to: {PAYPAL_ME_URL}")
    uvicorn.run(app, host="0.0.0.0", port=8765)
